### ISSUE TITLE
events missing fields - shows errors in logs.

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_cohortdatabase#14]
++ Fields list in snapshot record does not match fields list in 'cohort'. Record is missing fields: descriptionformat, component, timecreated, timemodified, visible, theme ++
* line 902 of /lib/classes/event/base.php: call to debugging()
* line 273 of /admin/tool/cohortdatabase/classes/sync.php: call to core\event\base->add_record_snapshot()
* line 53 of /admin/tool/cohortdatabase/classes/task/sync.php: call to tool_cohortdatabase_sync->sync()
* line 252 of /lib/cronlib.php: call to tool_cohortdatabase\task\sync->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()

**Comment by dcadiou** [comment]
These warnings happens when Moodle events are created at the end of operations, here :
* `admin/tool/cohortdatabase/classes/sync.php:274` after cohort members removals
* `admin/tool/cohortdatabase/classes/sync.php:346` after cohort member additions

In both situations, its the same statement that is used : `$event->add_record_snapshot('cohort',$cohort);`. But supplied variable `$cohort` doesn't contains all needed expected properties to create an event. 

Here `lib/classes/event/base.php:899`, we can see that 

* supplied properties, `array_keys((array)$record)`, are :
```php
Array
(
    [0] => idnumber
    [1] => id
    [2] => name
    [3] => description
    [4] => contextid
)
```

* expected properties, `array_keys($columns)`, are :
```php
Array
(
    [0] => id
    [1] => contextid
    [2] => name
    [3] => idnumber
    [4] => description
    [5] => descriptionformat
    [6] => visible
    [7] => component
    [8] => timecreated
    [9] => timemodified
    [10] => theme
)
```

It's not really a bug since it doesn't stop execution. However, its not as well written as expected.

The SQL query :
```sql
select from_unixtime(l.timecreated), l.*
from mdl_logstore_standard_log l 
where eventname like '_core_event_cohort_member_%'
order by timecreated desc;
```
shows that events are well recorded in standard log table, for instance.

These warnings only appears if debug options are enabled in `config.php` (see `if ($CFG->debugdeveloper) {` condition.

**Comment by danmarsden** [comment]
fixed in latest version.
