### ISSUE TITLE
Ability to set user group and sync memberships

### ISSUE THREAD

**Issue by cwarwicker** [catalyst/moodle-tool_cohortdatabase#15]
Hi,

My old workplace is looking at this plugin as a way of creating cohorts and syncing users into them from their student information system, but they would also like to be able to automatically create group memberships within the same process, e.g. by using the same sort of method you use for the cohort - setting a custom field (or multiple fields probbaly, as they might be in multiple groups) and mapping them to group idnumbers, then syncing users to those groups during the cohort sync. I advised them that the actual creation of groups will have to be done manually beforehand, but they would like this membership sync to happen during the same cohort process, to avoid having to have multiple processes to configure everything.

Is that something which you would be willing to add as a feature? Or, if not, if I extend the plugin for them, would you like me to do a PR so you can include it? 

Conn

**Comment by danmarsden** [comment]
Hey Conn - this sounds like something better suited to the enrolment plugin rather than cohortdatabase to me - I don't think it sits very well within the cohortdatabase plugin which only deals with site-level info (site cohorts) rather than course level info (groups/enrolments etc.)

I think what you're probably asking for is https://tracker.moodle.org/browse/MDL-58785  and you might even find this useful:
https://github.com/catalyst/moodle-local_enrolgroup

Keep in mind that plugin isn't massively tested - I wrote it for a client that ended up going in a different direction but it seemed to work in local testing.

Good luck!

**Comment by cwarwicker** [comment]
Cheers, I'll pass it onto them.
