### ISSUE TITLE
Coding errror detected warning and no removal of users

### ISSUE THREAD

**Issue by koenr** [catalyst/moodle-tool_cohortdatabase#8]
Moodle 3.7
When changing a users cohort in the external database, the warning:

!!! Coding error detected, it must be fixed by a programmer: Invalid context id specified context::instance_by_id() !!!
!! 
Error code: codingerror !!
!! Stack trace: * line 5184 of /lib/accesslib.php: coding_exception thrown
* line 334 of /admin/tool/cohortdatabase/classes/sync.php: call to context::instance_by_id()
* line 67 of /admin/tool/cohortdatabase/cli/sync.php: call to tool_cohortdatabase_sync-&gt;sync()
 !!

is thrown on the next run of the sync (and only then).

The user is added to the new cohort, but not removed from the old cohort.
I'm still testing the plugin and never succeeded to remove users from cohorts or remove empty cohorts using Moodle 3.7., so I'm not aware what behaviour is expected and what not. 

I'm writing up some documentation on https://docs.moodle.org/37/en/Cohort_external_database and translated the plugin to Dutch. Feel free to add / modify.

**Comment by danmarsden** [comment]
thanks @koenr - I haven't got anyone using this in 3.7 yet, good to know about that error thanks.

I suspect you might be running into this:
https://github.com/catalyst/moodle-tool_cohortdatabase/commit/e663e44f22c26569e8e47a6eb96e4993ea026ac9

When the cohort is completely empty it doesn't delete the cohort/remove users, just in case something bad has occurred - I did this because we had some issues where the external connection failed and returned an empty result which was in fact an "error" state and ended up removing all users from the cohort (in turn un-enrolling them from some courses and causing all sorts of problems.) - I suspect it may have occurred when the external table was being rebuilt.

I didn't get a chance to add some configuration to manage this or to notify when this occurs, feel free to file a pull request to improve that!

thanks!

**Comment by koenr** [comment]
Well, it's more then that: the user that has left the cohort, isn't removed from it, only added to the new one.
example:
Database:
a, cohort_a
b, cohort_b
-> works as expected.

If you change the database then to
a, cohort_a
b, cohort_a

Then it throws the error, adds b to cohort_a and leaves b in cohort_b as well - so b is then in 2 cohorts.

I see the dangers of the data failing to come thru - deleting is dangerous.I don't think I'm capable to fix any of the errors - my php skills are to limited - but I 'll have another look today.

**Comment by danmarsden** [comment]
If your cohort_b has other users in it, then the remove process should still work ok.

you could also try changing this line to "true"
https://github.com/catalyst/moodle-tool_cohortdatabase/blob/master/classes/sync.php#L227

but... be careful if you have other system level cohorts not created by the cohortdatabase tool because it may end up clearing those out too.

**Comment by koenr** [comment]
Thanks a lot for your suggestion! Changing the line to true makes it possible to move all users from one cohort to another. Empty cohorts don't get deleted. There seems to be no other way to delete them apart from removing them from the table mdl_cohort manually.
I created manually an extra system level cohort and that is never affected by anything in the external database, even if the name and cohortID are the same. Even if I try to add a user to it using the external database, a new cohort gets created. 
I'll add some more to the docs.

I changed the line containing  $foundexternalcohort = true;  to 
            if (empty($removeaction)) {
                   $foundexternalcohort = true;
            } else {
                   $foundexternalcohort = false;
            }
which gives the removeaction setting a better feel.

**Comment by danmarsden** [comment]
yeah - that is really behaviour that is specific to the clients we're using this with and should probably change in the core release. I think instead of wrapping it like that we should make the remove action have 3 options.
"never remove", "always remove", "Only remove if cohort contains other members"

There isn't a clean up process for empty cohorts either - it doesn't delete the cohort itself when it is in fact empty. That's something I've wanted to add.

**Comment by prouger** [comment]
Hi, 
The main issue for us is the changes in cohort's name. Each cohorts name change. So We have to clean up the long list of cohorts. 
Do you expect that your new delete function will erase the empty cohorts (with the good parameter) ? Otherwise is there another way to delete system cohorts (those created by plugin) Thanks in advance.

**Comment by danmarsden** [comment]
@prouger - I'm not actively working on this improvement - but feel free to submit a pull request or drop me a private message if you'd like to fund development.

**Comment by danmarsden** [comment]
this should be fixed in the incoming PR #17
